### PR TITLE
Fix error in __slots__ support of the __weakref__ attribute

### PR DESCRIPTION
**Pull request by dominicdoty**
Fix for #82 

Tests passing  in Python 3.7.9

### CODE REVIEW

**Comment by dominicdoty** [comment]
ran test pipelines on my fork, all passed:

[https://github.com/dominicdoty/pyjson_tricks/actions/runs/3365444659](https://github.com/dominicdoty/pyjson_tricks/actions/runs/3365444659)

**Comment by mverleg** [comment]
Thanks for providing a solution! I think I'll make some slight changes, because I'd prefer to handle this when encoding instead of decoding.

**Comment by dominicdoty** [comment]
I figured it maybe is a valid thing to encode and then confirm that the new object has the same attribute, since you potentially could have different behavior if someone changed the class definition to not include the __weakref__ attribute before decoding in a different environment.

But, that's probably too much of a corner case to care about.

If anyone finds this in the future because they have some jsons with this encoded in already - you can simply delete the __weakref__ attribute from your json to fix it.

**Comment by dominicdoty** [comment]
Works for me!

Thanks for taking care of this, glad to have it fixed either way.

**Pull request closed without merging**
